steps:
# Langkah 0: Bina Imej Docker
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${COMMIT_SHA}', '.']

# Langkah 1: Tolak Imej ke Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${COMMIT_SHA}']

# Langkah 2: Deploy ke Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - run
  - deploy
  - ${_SERVICE_NAME}
  - --image
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${COMMIT_SHA}
  - --region
  - ${_REGION}
  - --platform
  - managed
  - --allow-unauthenticated
  - --port
  - '8080'
  # Penyambung Rahsia
  - --update-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest
  
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: cryptorian-telebot

# PEMBETULAN RALAT LOG BARU INI: 
# Memaksa Cloud Build untuk menggunakan Cloud Logging dan BUKAN Bucket Storage yang bermasalah.
options:
  logging: CLOUD_LOGGING_ONLY
